/**
 * Soar File Templates
 *
 * Templates for generating Soar production files for operators and substates
 */

export class SoarTemplates {
  /**
   * Generate elaborations file for an operator
   */
  static generateElaborations(operatorName: string): string {
    return `###
### Elaborations for operator: ${operatorName}
###

sp {elaborate*${operatorName}*operator
   "Mark operator as ${operatorName}"
   (state <s> ^operator <op>)
   (<op> ^name ${operatorName})
-->
   (<s> ^${operatorName} <op>)
}

# Add additional elaboration rules here
`;
  }

  /**
   * Generate propose file for an operator
   */
  static generatePropose(operatorName: string, stateName: string): string {
    return `###
### Propose operator: ${operatorName}
###

sp {${stateName}*propose*${operatorName}
   (state <s> ^name ${stateName})
   # Add conditions here
-->
   (<s> ^operator <op> + =)
   (<op> ^name ${operatorName})
}
`;
  }

  /**
   * Generate apply file for an operator
   */
  static generateApply(operatorName: string): string {
    return `###
### Apply operator: ${operatorName}
###

sp {apply*${operatorName}
   (state <s> ^operator <op>)
   (<op> ^name ${operatorName})
-->
   (<s>)
}
`;
  }

  /**
   * Generate complete operator file (elaborations + propose + apply)
   */
  static generateOperatorFile(operatorName: string, stateName: string): string {
    return `sp {${stateName}*propose*${operatorName}
   (state <s> ^name ${stateName})
-->
   (<s> ^operator <op> + =)
   (<op> ^name ${operatorName})
}

sp {apply*${operatorName}
   (state <s> ^operator <op>)
   (<op> ^name ${operatorName})
-->
   (<s>)
}
`;
  }

  /**
   * Generate elaborations for a high-level operator (substate)
   */
  static generateSubstateElaborations(operatorName: string): string {
    return `###
### Elaborations for substate: ${operatorName}
###

sp {elaborate*${operatorName}*state
   "Copy superstate information to ${operatorName} substate"
   (state <s> ^superstate <ss>)
   (<ss> ^operator <op>)
   (<op> ^name ${operatorName})
-->
   (<s> ^name ${operatorName})
}

sp {elaborate*${operatorName}*top-state
   "Link to top-state"
   (state <s> ^superstate.top-state <ts>)
-->
   (<s> ^top-state <ts>)
}

sp {elaborate*${operatorName}*io
   "Link to io"
   (state <s> ^top-state.io <io>)
-->
   (<s> ^io <io>)
}
`;
  }

  /**
   * Generate propose for substate operator
   */
  static generateSubstatePropose(operatorName: string): string {
    return `###
### Propose substate operator: ${operatorName}
###

sp {propose*${operatorName}
   "Propose ${operatorName} substate operator"
   (state <s> ^superstate nil)  # Top state
   # Add conditions here
-->
   (<s> ^operator <op> +)
   (<op> ^name ${operatorName})
}
`;
  }

  /**
   * Generate selection rules for substate
   */
  static generateSubstateSelection(operatorName: string): string {
    return `###
### Selection rules for ${operatorName}
###

sp {select*${operatorName}*best
   "Select best ${operatorName} operator"
   (state <s> ^name ${operatorName}
              ^operator <op> +)
   # Add selection preferences here
-->
   (<s> ^operator <op> >)
}
`;
  }

  /**
   * Generate initialization file for substate
   */
  static generateSubstateInit(operatorName: string): string {
    return `###
### Initialization for substate: ${operatorName}
###

${this.generateSubstateElaborations(operatorName)}

# Add additional initialization rules here
`;
  }

  /**
   * Generate a simple production file
   */
  static generateProductionFile(fileName: string): string {
    const baseName = fileName.replace(/\.soar$/, '');
    return `###
### ${baseName}
### Generated by Soar VS Code Extension
###

# Add productions here

sp {${baseName}*example
   (state <s> ^superstate <ss>)
-->
   (write (crlf) |Production file: ${baseName}|)
}
`;
  }

  /**
   * Generate _firstload.soar file for a folder
   */
  static generateFirstLoad(folderName: string, files: string[]): string {
    const sourceCommands = files.map(file => `source ${file}`).join('\n');
    return `###
### First load file for: ${folderName}
### This file is sourced first when loading the ${folderName} folder
###

echo "Loading ${folderName}..."

${sourceCommands}

echo "${folderName} loaded."
`;
  }

  /**
   * Generate _all.soar file for a folder
   */
  static generateAllFile(folderName: string, subfolders: string[]): string {
    const pushCommands = subfolders
      .map(folder => `pushd ${folder}\nsource _all.soar\npopd`)
      .join('\n\n');
    return `###
### Load all files in ${folderName}
###

echo "Loading all ${folderName} files..."

# Load this folder
source _firstload.soar

# Load subfolders
${pushCommands}

echo "All ${folderName} files loaded."
`;
  }

  /**
   * Generate top-level load file
   */
  static generateTopLoad(projectName: string): string {
    return `###
### Top-level load file for ${projectName}
### Generated by Soar VS Code Extension
###

echo "Loading ${projectName}..."

# Source all files
pushd ${projectName}
source _all.soar
popd

echo "${projectName} loaded successfully."
`;
  }

  /**
   * Generate README for operator folder
   */
  static generateOperatorReadme(operatorName: string, isSubstate: boolean): string {
    const type = isSubstate ? 'High-Level Operator (Substate)' : 'Operator';
    return `# ${operatorName}

**Type:** ${type}

## Description

This ${type.toLowerCase()} handles [describe purpose here].

## Files

${
  isSubstate
    ? `
- **elaborations/**: Substate elaborations and initialization
- **_firstload.soar**: Load order for this operator
- **_all.soar**: Load all operator files
`
    : `
- **${operatorName}.soar**: Main operator file
`
}

## Usage

[Describe when and how this operator is used]

## Conditions

[Describe proposal conditions]

## Actions

[Describe what this operator does]
`;
  }
}
